const hugQuotes = ["Don’t be afraid. Be focused. Be determined. Be hopeful. Be empowered. - Michelle Obama", " You have always been there for me unconditionally. It's been a tough journey, but you're my inspiration. You are the one that I can go to when everything else seems hard or impossible in my life. Thank you for being here, friend!", "Thanks so much for always being around. It's a comment on how much we mean to each other. I'm so lucky to have such a wonderful friend who knows what I'm thinking without having to say a single word. I'm thankful to have you as a friend in my life!", "Thanks for all of the laughs, advice, and sweet (and naughty) memories throughout time. You are indeed a fantastic friend in my life who brings me happiness when I'm down. When I see you it's a sign that my life is back in control.", "I always hoped to have a friend like you. I can't account for why you like me so much, but I'm so thankful that you are in my life, and I appreciate all of our time together.", "True friends are there through the ups and downs, supporting each other through hard times and good times. Having you as my friend is one of the best things that could ever happen to me. Thank you for accepting me just as  I am. You're genuinely one of the best friends I've ever had, and only you would understand that!", "In case I haven't mentioned how important you are to me lately, my life would not be as great without your support and love lifting me up. Best friends listen first and foremost, and that's you. Thanks for always being a kind friend.", "You deserve a million thanks and all the hugs I can give.", "You are the best thing that ever happened to me. Thank you.", "You are one of the few people who have helped make me who I am today. Thank you for that.", "It's hard saying thanks to a person who deserves so much more than mere words. I hope I can repay even a part of the friendship you have given me."]
// i will move all generation front-end soon!
module.exports = {
	name: "hug",
	async execute(req, res) {
		const getRandomHugQuote = hugQuotes[Math.floor(Math.random() * hugQuotes.length)]
		const getRandomHugGif = Math.floor(Math.random() * 11) + 1
		return res.render("hug.ejs", { hug: getRandomHugGif, quote: getRandomHugQuote })
	}
}
